/*
 * fakelib/libobj.c
 *
 * Copyright © 2015 Simon Evans. All rights reserved.
 *
 * Fake Obj-c calls used by OSX/Mach-O libswiftCore
 *
 * Nothing here works!
 *
 */

#include "klibc.h"

UNIMPLEMENTED(CFErrorGetTypeID)
UNIMPLEMENTED(CFGetTypeID)
UNIMPLEMENTED(CFSetGetValues)
UNIMPLEMENTED(CFStringCompare)
UNIMPLEMENTED(CFStringCreateCopy)
UNIMPLEMENTED(CFStringCreateWithSubstring)
UNIMPLEMENTED(CFStringFindWithOptions)
UNIMPLEMENTED(CFStringGetCStringPtr)
UNIMPLEMENTED(CFStringGetCharacterAtIndex)
UNIMPLEMENTED(CFStringGetCharacters)
UNIMPLEMENTED(CFStringGetCharactersPtr)
UNIMPLEMENTED(CFStringGetLength)
UNIMPLEMENTED(NSClassFromString)
UNIMPLEMENTED(OBJC_CLASS_$_NSArray)
UNIMPLEMENTED(OBJC_CLASS_$_NSDictionary)
UNIMPLEMENTED(OBJC_CLASS_$_NSEnumerator)
UNIMPLEMENTED(OBJC_CLASS_$_NSError)
UNIMPLEMENTED(OBJC_CLASS_$_NSNumber)
UNIMPLEMENTED(OBJC_CLASS_$_NSObject)
UNIMPLEMENTED(OBJC_CLASS_$_NSProcessInfo)
UNIMPLEMENTED(OBJC_CLASS_$_NSSet)
UNIMPLEMENTED(OBJC_CLASS_$_NSString)
UNIMPLEMENTED(OBJC_METACLASS_$_NSArray)
UNIMPLEMENTED(OBJC_METACLASS_$_NSDictionary)
UNIMPLEMENTED(OBJC_METACLASS_$_NSEnumerator)
UNIMPLEMENTED(OBJC_METACLASS_$_NSError)
UNIMPLEMENTED(OBJC_METACLASS_$_NSObject)
UNIMPLEMENTED(OBJC_METACLASS_$_NSSet)
UNIMPLEMENTED(OBJC_METACLASS_$_NSString)
UNIMPLEMENTED(__CFConstantStringClassReference)
UNIMPLEMENTED(_objc_empty_cache)
UNIMPLEMENTED(_objc_rootAutorelease)
UNIMPLEMENTED(class_conformsToProtocol)
UNIMPLEMENTED(class_copyIvarList)
UNIMPLEMENTED(class_createInstance)
UNIMPLEMENTED(class_getInstanceSize)
UNIMPLEMENTED(class_getName)
UNIMPLEMENTED(class_getSuperclass)
UNIMPLEMENTED(class_isMetaClass)
UNIMPLEMENTED(class_respondsToSelector)
UNIMPLEMENTED(ivar_getOffset)
UNIMPLEMENTED(objc_autorelease)
UNIMPLEMENTED(objc_autoreleaseReturnValue)
UNIMPLEMENTED(objc_copyWeak)
UNIMPLEMENTED(objc_debug_isa_class_mask)
UNIMPLEMENTED(objc_destroyWeak)
UNIMPLEMENTED(objc_destructInstance)
UNIMPLEMENTED(objc_initWeak)
UNIMPLEMENTED(objc_loadWeakRetained)
UNIMPLEMENTED(objc_moveWeak)
UNIMPLEMENTED(objc_msgSend)
UNIMPLEMENTED(objc_msgSendSuper2)
UNIMPLEMENTED(objc_msgSend_stret)
UNIMPLEMENTED(objc_readClassPair)
UNIMPLEMENTED(objc_release)
UNIMPLEMENTED(objc_retain)
UNIMPLEMENTED(objc_retainAutoreleasedReturnValue)
UNIMPLEMENTED(objc_storeWeak)
UNIMPLEMENTED(object_dispose)
UNIMPLEMENTED(object_getClass)
UNIMPLEMENTED(protocol_getName)
UNIMPLEMENTED(sel_getName)
